/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'materi-ajar': RouteRecordInfo<'materi-ajar', '/materi-ajar', Record<never, never>, Record<never, never>>,
    'referensi-mata-pelajaran': RouteRecordInfo<'referensi-mata-pelajaran', '/referensi/mata-pelajaran', Record<never, never>, Record<never, never>>,
    'referensi-pembelajaran': RouteRecordInfo<'referensi-pembelajaran', '/referensi/pembelajaran', Record<never, never>, Record<never, never>>,
    'referensi-ptk': RouteRecordInfo<'referensi-ptk', '/referensi/ptk', Record<never, never>, Record<never, never>>,
    'referensi-rombel': RouteRecordInfo<'referensi-rombel', '/referensi/rombel', Record<never, never>, Record<never, never>>,
    'referensi-sekolah': RouteRecordInfo<'referensi-sekolah', '/referensi/sekolah', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'settings-permissions': RouteRecordInfo<'settings-permissions', '/settings/permissions', Record<never, never>, Record<never, never>>,
    'settings-profile': RouteRecordInfo<'settings-profile', '/settings/profile', Record<never, never>, Record<never, never>>,
    'settings-users-roles': RouteRecordInfo<'settings-users-roles', '/settings/users-roles', Record<never, never>, Record<never, never>>,
  }
}
