/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'materi-ajar': RouteRecordInfo<'materi-ajar', '/materi-ajar', Record<never, never>, Record<never, never>>,
    'materi-ajar-id': RouteRecordInfo<'materi-ajar-id', '/materi-ajar/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'materi-ajar-tambah': RouteRecordInfo<'materi-ajar-tambah', '/materi-ajar/tambah', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pelatihan': RouteRecordInfo<'pelatihan', '/pelatihan', Record<never, never>, Record<never, never>>,
    'pelatihan-id': RouteRecordInfo<'pelatihan-id', '/pelatihan/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-aksi-id': RouteRecordInfo<'pelatihan-aksi-id', '/pelatihan/aksi/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-id': RouteRecordInfo<'pelatihan-sesi-id', '/pelatihan/sesi/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-pelatihan_id': RouteRecordInfo<'pelatihan-sesi-pelatihan_id', '/pelatihan/sesi/:pelatihan_id', { pelatihan_id: ParamValue<true> }, { pelatihan_id: ParamValue<false> }>,
    'pelatihan-sesi-tambah-id': RouteRecordInfo<'pelatihan-sesi-tambah-id', '/pelatihan/sesi/tambah/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-tambah-pelatihan_id': RouteRecordInfo<'pelatihan-sesi-tambah-pelatihan_id', '/pelatihan/sesi/tambah/:pelatihan_id', { pelatihan_id: ParamValue<true> }, { pelatihan_id: ParamValue<false> }>,
    'pelatihan-tambah': RouteRecordInfo<'pelatihan-tambah', '/pelatihan/tambah', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'referensi-mata-pelajaran': RouteRecordInfo<'referensi-mata-pelajaran', '/referensi/mata-pelajaran', Record<never, never>, Record<never, never>>,
    'referensi-ptk': RouteRecordInfo<'referensi-ptk', '/referensi/ptk', Record<never, never>, Record<never, never>>,
    'referensi-rombel': RouteRecordInfo<'referensi-rombel', '/referensi/rombel', Record<never, never>, Record<never, never>>,
    'referensi-sekolah': RouteRecordInfo<'referensi-sekolah', '/referensi/sekolah', Record<never, never>, Record<never, never>>,
    'settings-permissions': RouteRecordInfo<'settings-permissions', '/settings/permissions', Record<never, never>, Record<never, never>>,
    'settings-users-roles': RouteRecordInfo<'settings-users-roles', '/settings/users-roles', Record<never, never>, Record<never, never>>,
  }
}
