/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'asesmen-mata-pelajaran': RouteRecordInfo<'asesmen-mata-pelajaran', '/asesmen/mata-pelajaran', Record<never, never>, Record<never, never>>,
    'asesmen-pembelajaran': RouteRecordInfo<'asesmen-pembelajaran', '/asesmen/pembelajaran', Record<never, never>, Record<never, never>>,
    'asesmen-tes': RouteRecordInfo<'asesmen-tes', '/asesmen/tes', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'dokumen': RouteRecordInfo<'dokumen', '/dokumen', Record<never, never>, Record<never, never>>,
    'galeri-slug': RouteRecordInfo<'galeri-slug', '/galeri/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'konten-ptk': RouteRecordInfo<'konten-ptk', '/konten/ptk', Record<never, never>, Record<never, never>>,
    'konten-slide': RouteRecordInfo<'konten-slide', '/konten/slide', Record<never, never>, Record<never, never>>,
    'konten-visi-misi': RouteRecordInfo<'konten-visi-misi', '/konten/visi-misi', Record<never, never>, Record<never, never>>,
    'laman-galeri': RouteRecordInfo<'laman-galeri', '/laman/galeri', Record<never, never>, Record<never, never>>,
    'laman-kontak': RouteRecordInfo<'laman-kontak', '/laman/kontak', Record<never, never>, Record<never, never>>,
    'laman-program': RouteRecordInfo<'laman-program', '/laman/program', Record<never, never>, Record<never, never>>,
    'laman-tentang': RouteRecordInfo<'laman-tentang', '/laman/tentang', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'materi': RouteRecordInfo<'materi', '/materi', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'page-galeri': RouteRecordInfo<'page-galeri', '/page/galeri', Record<never, never>, Record<never, never>>,
    'page-kontak': RouteRecordInfo<'page-kontak', '/page/kontak', Record<never, never>, Record<never, never>>,
    'page-program': RouteRecordInfo<'page-program', '/page/program', Record<never, never>, Record<never, never>>,
    'page-tentang': RouteRecordInfo<'page-tentang', '/page/tentang', Record<never, never>, Record<never, never>>,
    'pelatihan': RouteRecordInfo<'pelatihan', '/pelatihan', Record<never, never>, Record<never, never>>,
    'pelatihan-id': RouteRecordInfo<'pelatihan-id', '/pelatihan/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-aksi-id': RouteRecordInfo<'pelatihan-aksi-id', '/pelatihan/aksi/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-id': RouteRecordInfo<'pelatihan-sesi-id', '/pelatihan/sesi/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-edit-id': RouteRecordInfo<'pelatihan-sesi-edit-id', '/pelatihan/sesi/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-materi-id': RouteRecordInfo<'pelatihan-sesi-materi-id', '/pelatihan/sesi/materi/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-materi-edit-id': RouteRecordInfo<'pelatihan-sesi-materi-edit-id', '/pelatihan/sesi/materi/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-materi-tambah-id': RouteRecordInfo<'pelatihan-sesi-materi-tambah-id', '/pelatihan/sesi/materi/tambah/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-tambah-id': RouteRecordInfo<'pelatihan-sesi-tambah-id', '/pelatihan/sesi/tambah/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-tes-formatif-id': RouteRecordInfo<'pelatihan-sesi-tes-formatif-id', '/pelatihan/sesi/tes-formatif/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-tes-formatif-edit-id': RouteRecordInfo<'pelatihan-sesi-tes-formatif-edit-id', '/pelatihan/sesi/tes-formatif/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-tes-formatif-tambah-id': RouteRecordInfo<'pelatihan-sesi-tes-formatif-tambah-id', '/pelatihan/sesi/tes-formatif/tambah/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-tugas-id': RouteRecordInfo<'pelatihan-sesi-tugas-id', '/pelatihan/sesi/tugas/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-tugas-edit-id': RouteRecordInfo<'pelatihan-sesi-tugas-edit-id', '/pelatihan/sesi/tugas/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-sesi-tugas-tambah-id': RouteRecordInfo<'pelatihan-sesi-tugas-tambah-id', '/pelatihan/sesi/tugas/tambah/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pelatihan-tambah': RouteRecordInfo<'pelatihan-tambah', '/pelatihan/tambah', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'program-slug': RouteRecordInfo<'program-slug', '/program/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'referensi-pembelajaran': RouteRecordInfo<'referensi-pembelajaran', '/referensi/pembelajaran', Record<never, never>, Record<never, never>>,
    'referensi-sekolah': RouteRecordInfo<'referensi-sekolah', '/referensi/sekolah', Record<never, never>, Record<never, never>>,
    'referensi-sekolah-old': RouteRecordInfo<'referensi-sekolah-old', '/referensi/sekolah_old', Record<never, never>, Record<never, never>>,
    'referensi-tes': RouteRecordInfo<'referensi-tes', '/referensi/tes', Record<never, never>, Record<never, never>>,
    'sesi': RouteRecordInfo<'sesi', '/sesi', Record<never, never>, Record<never, never>>,
    'settings-permissions': RouteRecordInfo<'settings-permissions', '/settings/permissions', Record<never, never>, Record<never, never>>,
    'settings-users-roles': RouteRecordInfo<'settings-users-roles', '/settings/users-roles', Record<never, never>, Record<never, never>>,
  }
}
