<table border="1">
    <thead>
        <tr>
            <th>no</th>
            <th>nama</th>
            <th>nipd</th>
            <th>nisn</th>
            <th>jenis_kelamin</th>
            <th>tempat_lahir</th>
            <th>tanggal_lahir</th>
            <th>agama</th>
            <th>alamat</th>
            <th>telepon</th>
            <th>nama_ayah</th>
            <th>agama_ayah</th>
            <th>pekerjaan_ayah</th>
            <th>nama_ibu</th>
            <th>agama_ibu</th>
            <th>pekerjaan_ibu</th>
            <th>nama_wali</th>
            <th>agama_wali</th>
            <th>pekerjaan_wali</th>
            <th>alamat_wali</th>
            <th>sekolah_asal</th>
            <th>tanggal_diterima</th>
            <th>nomor_surat_pindah</th>
            <th>nipd_asal</th>
            <th>program_pilihan</th>
            <th>nilai_un</th>
        </tr>
    </thead>
    <tbody>
        @for ($i = 0; $i < 50; $i++)
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        @endfor
    </tbody>
</table>
